<a href="https://colab.research.google.com/github/TheBProgrammer/Image-Processing/blob/main/Task_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import urllib.request
urllib.request.urlretrieve('https://raw.githubusercontent.com/guiwitz/PyImageCourse_beginner/master/svg.py', 'svg.py')
from svg import numpy_to_svg

In [2]:
myarray = np.zeros((4,6))

In [3]:
numpy_to_svg(myarray)

In [4]:
myarray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
myarray[3,2] = 13

In [6]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
myarray = myarray + 32
myarray

array([[32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32.],
       [32., 32., 45., 32., 32., 32.]])

In [8]:
for x in range(4):
    for y in range(6):
        myarray[x,y] = myarray[x,y] + 15

In [9]:
myarray

array([[47., 47., 47., 47., 47., 47.],
       [47., 47., 47., 47., 47., 47.],
       [47., 47., 47., 47., 47., 47.],
       [47., 47., 60., 47., 47., 47.]])

In [10]:
myarray1 = 2*np.ones((4,4))
myarray2 = 5*np.ones((4,4))
myarray3 = myarray1 * myarray2
myarray3

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [11]:
myarray = np.ones((5,10))
numpy_to_svg(myarray)

In [12]:
myarray.sum()

50.0

In [13]:
myarray = np.zeros((4,4))
myarray[2,3] = 1
myarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [14]:
myarray > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])